name: "Execução Manual - n1"

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

       # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn
      
      # instalação das dependências
      - name: Instalando dependências
        run: yarn
      
      # instalação do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      - name: Executando Testes E2E
        run: yarn run e2e
        working-directory: trabalho-final-programacao/testes